USE acadhub;

ALTER TABLE USERS ADD phone VARCHAR(15);
ALTER TABLE STUDENT ADD cgpa DECIMAL(4,2);
ALTER TABLE ASSESSMENT ADD passing_marks INT DEFAULT 20;
ALTER TABLE COURSE ADD description VARCHAR(255);